- name: configure webserver with nginx
  hosts: web
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: install nginx
      yum:
        name: nginx
        update_cache: yes
        state: present

    - name: create ssl directories
      file:
        path: /etc/nginx/ssl
        state: directory

    - name: copy tls key
      copy:
        src: files/nginx.key
        dest: "{{ key_file }}"
        owner: root
        mode: 0600
        notify: restart nginx

    - name: copy tls certificate
      copy:
        src: files/nginx.crt
        dest: "{{ cert_file }}"
        notify: restart nginx

    - name: copy nginx config file
      template:
        src: templates/nginx.conf.j2
        dest: "{{ conf_file }}"
        notify: restart nginx

    - name: copy index html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
# no tls
# - name: create sites-available directory
# file:
# path: /etc/nginx/sites-available
# state: directory
# owner: ktisdale
# group: ktisdale
# mode: "755"
# recurse: yes

# - name: create the sites-enabled directory
# file:
# path: /etc/nginx/sites-enabled
# state: directory
# owner: ktisdale
# group: ktisdale
# mode: "755"
# recurse: yes

# - name: copy nginx file
# copy:
# src: files/nginx.conf
# dest: /etc/nginx/sites-available/default
#owner: ktisdale
#group: ktisdale
#mode: "755"

# - name: enable configuration
# file:
# dest: /etc/nginx/sites-enabled/default
# src: /etc/nginx/sites-available/default
# state: link

# - name: copy index.html
# template:
# src: templates/index.html.j2
# dest: /usr/share/nginx/html/index.html
# mode: "755"

#- name: restart nginx
# service:
# name: nginx
# state: restarted
