- name: configure webserver with nginx
  hosts: web
  become: True
  tasks:
    - name: install nginx
      yum:
        name: nginx
        update_cache: yes
        state: present

    - name: create sites-available directory
      file:
        path: /etc/nginx/sites-available/default
        state: directory
        owner: ktisdale
        group: ktisdale
        mode: "755"
        recurse: yes

    - name: create the sites-enabled directory
      file:
        path: /etc/nginx/sites-enabled/default
        state: directory
        owner: ktisdale
        group: ktisdale
        mode: "755"
        recurse: yes

    - name: copy nginx file
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        owner: ktisdale
        group: ktisdale
        mode: "755"

    - name: enable configuration
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: "755"

    - name: restart nginx
      service:
        name: nginx
        state: restarted
