---
- name: enable internet services
  hosts: web
  become: yes

  tasks:

  - name: latest version of required packages
    yum:
      name:
        - firewalld
        - httpd
        - mariadb
        - php
        - php-mysql
      state: latest

  - name: firewalld enabled and running
    systemd:
      name: firewalld
      enabled: true
      state: started
      masked: no

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: httpd enabled and running
    systemd:
      name: httpd
      enabled: true
      state: started

  - name: mariadb enabled and running
    systemd:
      name: mariadb
      enabled: true
      state: started
      masked: no

  - name: test php page is installed
    get_url:
      url: "http://10.62.56.224/grading/var/www/html/index.php"
      dest: /var/www/html/index.php
      mode: 0644

- name: Test internet web server
  hosts: localhost
  become: no

  tasks:
    - name: connect to internet web server
      uri:
        url: http://10.62.56.224
        status_code: 200
